/**
 * Live APMC Market Prices Service
 * Fetches structured prices generated by apmc_kopargaon_scraper.py
 */

export interface ScrapedPriceRow {
  commodity: string;
  variety: string | null;
  unit: string | null;
  min_price: string;
  max_price: string;
  modal_price: string;
  arrival_qty: string;
  date: string | null;
  raw_cells: string[];
}

export interface APMCPricesPayload {
  category: string;
  date: string;
  scraped_at_utc: string;
  row_count: number;
  source_url: string;
  rows: ScrapedPriceRow[];
}

export async function fetchLiveAPMCPricesPayload(): Promise<APMCPricesPayload | null> {
  try {
    const response = await fetch('/data/prices.json');
    if (!response.ok) {
      throw new Error(`HTTP error ${response.status}: ${response.statusText}`);
    }
    const data = await response.json();
    if (data && typeof data === 'object' && Array.isArray(data.rows)) {
      return data as APMCPricesPayload;
    }
    return null;
  } catch (error) {
    console.error('Error fetching live APMC market prices payload:', error);
    return null;
  }
}

export async function fetchLiveAPMCPrices(): Promise<ScrapedPriceRow[]> {
  const payload = await fetchLiveAPMCPricesPayload();
  return payload ? payload.rows : [];
}
